-- ============================================================================
-- SOUNDBIRTH — Catálogo: etapas das duas jornadas e questionários
-- Correr depois de 01_schema.sql. Pode voltar a correr-se: atualiza o que
-- já existe (on conflict ... do update).
--
-- Sobre os itens dos questionários:
--   Os instrumentos publicados (CIQOL, SSQ, APHAB, APSQ, MuRQoL, LittlEARS,
--   PEACH...) estão protegidos por direitos de autor. Os itens que aqui ficam
--   para esses instrumentos são DE DEMONSTRAÇÃO — servem para testar o
--   circuito completo (envio → resposta → pontuação → alerta) e têm de ser
--   substituídos pelo texto e pela regra de pontuação da versão portuguesa
--   licenciada antes de qualquer uso clínico. A definição marca-os com
--   "demonstracao": true e a plataforma mostra esse aviso no formulário.
--   Os instrumentos locais (PREM, esforço auditivo, transição) têm itens
--   definitivos, escritos para este centro.
-- ============================================================================


-- ============================================================================
-- 1. ETAPAS — ADULTO (6 fases, 22 etapas)
-- ============================================================================
insert into etapas_modelo
  (id, grupo, fase, fase_curta, fase_ordem, ordem, titulo, titulo_simples, quem, prazo_texto, prazo_dias, nota, evidencia)
values
-- Fase 1
('a_ref', 'adulto', 'Referenciação e primeira avaliação', 'Referenciação', 1, 1,
 'Referenciação ao CREIC', 'O pedido chegou ao centro',
 'Médico assistente / ORL de origem', '—', null,
 'Entrada por consulta externa, consulta de próteses auditivas ou referenciação interna.',
 'Poucos candidatos chegam a ser referenciados: critérios pouco claros e barreiras na passagem da consulta de próteses para o centro de implantes (Ebrahimi-Madiseh et al., 2023).'),
('a_orl1', 'adulto', 'Referenciação e primeira avaliação', 'Referenciação', 1, 2,
 'Primeira consulta de ORL', 'Primeira consulta com o otorrino',
 'ORL do CREIC', 'até 60 dias', 60,
 'História clínica, otoscopia e definição do plano de estudo.', null),
('a_audio1', 'adulto', 'Referenciação e primeira avaliação', 'Referenciação', 1, 3,
 'Avaliação audiológica de base', 'Testes de audição completos',
 'Audiologia', 'até 30 dias', 30,
 'Audiograma tonal e vocal, impedanciometria; PEATC quando indicado.', null),
-- Fase 2
('a_protese', 'adulto', 'Otimização protésica e estudo de candidatura', 'Candidatura', 2, 1,
 'Adaptação e prova de próteses auditivas', 'Experimentar próteses bem ajustadas',
 'Audiologia', '3 meses de prova', 105,
 'Prova documentada, com verificação em orelha real. APHAB no início e no fim da prova.',
 'O APHAB documenta, do ponto de vista do doente, o benefício insuficiente com prótese bem adaptada — que é o que sustenta a indicação.'),
('a_campo', 'adulto', 'Otimização protésica e estudo de candidatura', 'Candidatura', 2, 2,
 'Reavaliação em campo livre com prótese', 'Novos testes com as próteses',
 'Audiologia', 'até 30 dias após a prova', 30,
 'Ganho funcional e discriminação vocal no silêncio e no ruído, com prótese.', null),
('a_imagem', 'adulto', 'Otimização protésica e estudo de candidatura', 'Candidatura', 2, 3,
 'TC dos ossos temporais e RM', 'Exames de imagem aos ouvidos',
 'Neurorradiologia', 'até 45 dias', 45,
 'Permeabilidade coclear, malformações, nervo coclear.', null),
('a_etiologia', 'adulto', 'Otimização protésica e estudo de candidatura', 'Candidatura', 2, 4,
 'Estudo etiológico e genético', 'Perceber a causa da surdez',
 'ORL / Genética', 'variável', 90,
 'Orienta o prognóstico e o aconselhamento familiar.', null),
('a_fala', 'adulto', 'Otimização protésica e estudo de candidatura', 'Candidatura', 2, 5,
 'Avaliação de terapia da fala e linguagem', 'Consulta de terapia da fala',
 'Terapia da fala', 'até 45 dias', 45,
 'Perfil comunicativo, modo de comunicação preferido e potencial de reabilitação.', null),
('a_psico', 'adulto', 'Otimização protésica e estudo de candidatura', 'Candidatura', 2, 6,
 'Avaliação de psicologia', 'Consulta de psicologia',
 'Psicologia', 'até 45 dias', 45,
 'Motivação, suporte familiar, humor (HADS) e fatores psicossociais.', null),
('a_expectativas', 'adulto', 'Otimização protésica e estudo de candidatura', 'Candidatura', 2, 7,
 'Expectativas e aconselhamento pré-implante', 'Falar sobre o que esperar do implante',
 'Audiologia + ORL', 'antes da reunião de decisão', 30,
 'CIQOL-Expectations antes e depois da consulta de aconselhamento; comparar cada domínio com os valores de utilizadores experientes.',
 'Os candidatos esperam, em média, mais do que os utilizadores experientes conseguem em comunicação (d = 0,78) e esforço auditivo (d = 0,88); só 18,6% dos utilizadores experientes atinge a expectativa média de esforço auditivo. As expectativas são modificáveis (McRackan et al., 2022).'),
('a_preop', 'adulto', 'Otimização protésica e estudo de candidatura', 'Candidatura', 2, 8,
 'Avaliação pré-operatória e vacinação', 'Exames antes da cirurgia e vacina',
 'Anestesiologia / Saúde pública', 'antes da cirurgia', 60,
 'Risco anestésico e vacinação antipneumocócica. DHI se houver queixas de tontura.', null),
-- Fase 3
('a_reuniao', 'adulto', 'Decisão', 'Decisão', 3, 1,
 'Reunião do grupo de implante coclear', 'A equipa reúne-se para decidir',
 'Equipa multidisciplinar', 'reunião seguinte', 30,
 'Decisão registada: candidato, não candidato, adiar ou rever.', null),
('a_decisao', 'adulto', 'Decisão', 'Decisão', 3, 2,
 'Consulta de decisão partilhada e consentimento', 'Decidir consigo',
 'ORL + gestor de caso', 'até 15 dias', 15,
 'Lado, dispositivo, riscos e benefícios; discutir as expectativas registadas face aos resultados típicos.',
 'Numa revisão de 357 estudos sobre modelos de cuidados em implante coclear no adulto, só 1 abordou a decisão partilhada (Ebrahimi-Madiseh et al., 2023).'),
('a_lista', 'adulto', 'Decisão', 'Decisão', 3, 3,
 'Inscrição em lista cirúrgica', 'Entrada na lista para cirurgia',
 'Secretariado clínico', 'no próprio dia', 7,
 'Com a prioridade definida pela equipa.', null),
-- Fase 4
('a_cirurgia', 'adulto', 'Cirurgia', 'Cirurgia', 4, 1,
 'Cirurgia de implantação', 'A cirurgia',
 'ORL / Bloco operatório', 'TMRG de cirurgia programada', 180,
 'Telemetria intraoperatória.',
 'Na idade ativa, implantar mais cedo aumenta o benefício líquido para a sociedade: cerca de €337 000 com indicação aos 30 anos, €114 000 aos 60 (modelo neerlandês; Neve et al., 2021).'),
('a_penso', 'adulto', 'Cirurgia', 'Cirurgia', 4, 2,
 'Consulta de penso e cicatrização', 'Ver a cicatriz',
 'Enfermagem / ORL', '7 a 10 dias', 10,
 'Avaliação da ferida e ensino de cuidados.', null),
-- Fase 5
('a_ativacao', 'adulto', 'Ativação e programação', 'Ativação', 5, 1,
 'Ativação do processador', 'Ligar o processador pela primeira vez',
 'Audiologia', '3 a 4 semanas após a cirurgia', 35,
 'Primeiro mapa, ensino do dispositivo e da manutenção. Registo do processador entregue.', null),
('a_maps', 'adulto', 'Ativação e programação', 'Ativação', 5, 2,
 'Programações seriadas', 'Afinar o som, sessão a sessão',
 'Audiologia', '1 semana · 1 · 3 · 6 · 12 meses', 400,
 'Ajuste de níveis, leitura do datalogging (horas de uso) e resolução de queixas.', null),
-- Fase 6
('a_reabilitacao', 'adulto', 'Reabilitação e resultados', 'Reabilitação', 6, 1,
 'Reabilitação auditiva', 'Treinar a escuta',
 'Terapia da fala', 'semanal ou quinzenal', 400,
 'Plano individual com treino em casa. Considerar treino musical se o MuRQoL o indicar.', null),
('a_resultados', 'adulto', 'Reabilitação e resultados', 'Reabilitação', 6, 2,
 'Avaliação de resultados aos 3, 6 e 12 meses', 'Medir o que mudou',
 'Audiologia + equipa', 'marcos fixos', 400,
 'Testes vocais no silêncio e no ruído; CIQOL-10, SSQ12, HUI-3 e PREM em cada marco; CIQOL-35 aos 12 meses; situação profissional.',
 'O reconhecimento da fala explica só 10–20% da qualidade de vida medida com instrumentos genéricos, e 5–6% com instrumentos específicos de implante (McRackan et al., 2018). Os testes de cabine não chegam para medir o resultado.'),
('a_longo', 'adulto', 'Reabilitação e resultados', 'Reabilitação', 6, 3,
 'Seguimento anual', 'Consulta anual',
 'Equipa do CREIC', 'anual', null,
 'Manutenção, acessórios, avaliação de segundo implante; CIQOL-10, IOI-CI e HUI-3.', null),
('a_upgrade', 'adulto', 'Reabilitação e resultados', 'Reabilitação', 6, 4,
 'Reavaliação e atualização do processador', 'Experimentar um processador mais recente',
 'Audiologia', 'a cada 5 a 6 anos', null,
 'Testes vocais e APHAB + APSQ com o processador antigo e após 4 semanas com o novo. Há benefício se melhorar a fala (≥ 20 pp em monossílabos ou ≥ 2 dB no ruído) OU se APHAB ≥ 3,8 pp ou APSQ ≥ 0,74.',
 'Em 99 doentes, 35–42% relataram benefício relevante da atualização sem melhoria nos testes vocais. Só os PROMs o documentam — e são o argumento perante quem financia (Lailach et al., 2023).')
on conflict (id) do update set
  grupo = excluded.grupo, fase = excluded.fase, fase_curta = excluded.fase_curta,
  fase_ordem = excluded.fase_ordem, ordem = excluded.ordem, titulo = excluded.titulo,
  titulo_simples = excluded.titulo_simples, quem = excluded.quem, prazo_texto = excluded.prazo_texto,
  prazo_dias = excluded.prazo_dias, nota = excluded.nota, evidencia = excluded.evidencia;


-- ============================================================================
-- 2. ETAPAS — PEDIÁTRICO (7 fases, 25 etapas)
-- ============================================================================
insert into etapas_modelo
  (id, grupo, fase, fase_curta, fase_ordem, ordem, titulo, titulo_simples, quem, prazo_texto, prazo_dias, nota, evidencia)
values
-- Fase 1
('p_rastreio', 'pediatrico', 'Deteção e diagnóstico', 'Deteção', 1, 1,
 'Rastreio auditivo neonatal universal', 'O teste de audição na maternidade',
 'Maternidade', '1.º mês de vida', null,
 'Otoemissões e/ou PEATC automático antes da alta da maternidade.', null),
('p_reteste', 'pediatrico', 'Deteção e diagnóstico', 'Deteção', 1, 2,
 'Reteste e referenciação ao CREIC', 'Repetir o teste e vir ao centro',
 'ORL de origem', 'até 1 mês', 30,
 'Um rastreio que não passa não é diagnóstico — confirma-se sempre.', null),
('p_diagnostico', 'pediatrico', 'Deteção e diagnóstico', 'Deteção', 1, 3,
 'Diagnóstico audiológico', 'Confirmar o diagnóstico',
 'Audiologia pediátrica', 'até aos 3 meses de idade', 60,
 'PEATC por frequências, ASSR, otoemissões, impedanciometria.', null),
-- Fase 2
('p_protese', 'pediatrico', 'Intervenção precoce e próteses', 'Intervenção', 2, 1,
 'Adaptação de próteses auditivas', 'Próteses auditivas',
 'Audiologia pediátrica', 'até aos 6 meses de idade', 90,
 'Ganho verificado em orelha real; moldes renovados à medida que a orelha cresce.', null),
('p_precoce', 'pediatrico', 'Intervenção precoce e próteses', 'Intervenção', 2, 2,
 'Intervenção precoce e apoio à família', 'Apoio à família desde o início',
 'Terapia da fala / SNIPI', 'imediato', 30,
 'A família aprende a criar um ambiente rico em linguagem — o fator que mais pesa no resultado.', null),
('p_modo', 'pediatrico', 'Intervenção precoce e próteses', 'Intervenção', 2, 3,
 'Escolha informada do modo de comunicação', 'Escolher como comunicar em família',
 'Equipa + família', 'contínuo', null,
 'Oral, bilingue (LGP e oral) ou gestual: decisão da família, revista ao longo do tempo.', null),
-- Fase 3
('p_imagem', 'pediatrico', 'Estudo de candidatura', 'Candidatura', 3, 1,
 'TC dos ossos temporais e RM', 'Exames de imagem aos ouvidos',
 'Neurorradiologia', 'até 45 dias', 45,
 'Malformações da cóclea, nervo coclear, aqueduto vestibular.', null),
('p_genetica', 'pediatrico', 'Estudo de candidatura', 'Candidatura', 3, 2,
 'Estudo genético e etiológico', 'Perceber a causa da surdez',
 'Genética', 'variável', 90,
 'GJB2/GJB6 e painel alargado; aconselhamento aos pais.', null),
('p_oftalmo', 'pediatrico', 'Estudo de candidatura', 'Candidatura', 3, 3,
 'Avaliação oftalmológica', 'Consulta dos olhos',
 'Oftalmologia', 'até 60 dias', 60,
 'Exclui síndrome de Usher e garante a visão — o canal de aprendizagem enquanto não ouve.', null),
('p_desenv', 'pediatrico', 'Estudo de candidatura', 'Candidatura', 3, 4,
 'Avaliação do desenvolvimento e da linguagem', 'Avaliar o desenvolvimento',
 'Terapia da fala / Pediatria', 'até 45 dias', 45,
 'Marcos de desenvolvimento, comunicação pré-verbal, perturbações associadas.', null),
('p_psico', 'pediatrico', 'Estudo de candidatura', 'Candidatura', 3, 5,
 'Avaliação de psicologia e da família', 'Consulta de psicologia com a família',
 'Psicologia', 'até 45 dias', 45,
 'Expectativas da família, capacidade de adesão à reabilitação, suporte social.', null),
('p_preop', 'pediatrico', 'Estudo de candidatura', 'Candidatura', 3, 6,
 'Avaliação pré-operatória e vacinação', 'Exames antes da cirurgia e vacina',
 'Pediatria / Anestesiologia', 'antes da cirurgia', 60,
 'Vacinação antipneumocócica completa antes da implantação.', null),
-- Fase 4
('p_reuniao', 'pediatrico', 'Decisão e cirurgia', 'Cirurgia', 4, 1,
 'Reunião do grupo de implante coclear', 'A equipa reúne-se para decidir',
 'Equipa multidisciplinar', 'reunião seguinte', 30,
 'Candidatura, lateralidade e prioridade na lista.', null),
('p_consent', 'pediatrico', 'Decisão e cirurgia', 'Cirurgia', 4, 2,
 'Consulta de decisão e consentimento', 'Decidir em família',
 'ORL + gestor de caso', 'até 15 dias', 15,
 'Consentimento dos titulares das responsabilidades parentais; a criança é ouvida conforme a idade.', null),
('p_cirurgia', 'pediatrico', 'Decisão e cirurgia', 'Cirurgia', 4, 3,
 'Cirurgia de implantação', 'A cirurgia',
 'ORL / Bloco pediátrico', 'idealmente antes dos 12–18 meses', 90,
 'Bilateral simultânea sempre que indicado: uma anestesia, audição nos dois lados desde o início.',
 'Em crianças com surdez pré-lingual, o implante bilateral simultâneo aos 12 meses teve benefício líquido estimado de €433 000 ao longo da vida, e o bilateral face ao unilateral custou €34 000 por QALY — abaixo do limiar de €50 000 (Neve et al., 2021).'),
('p_penso', 'pediatrico', 'Decisão e cirurgia', 'Cirurgia', 4, 4,
 'Consulta de penso e cicatrização', 'Ver a cicatriz',
 'Enfermagem / ORL', '7 a 10 dias', 10,
 'Avaliação da ferida e ensino de cuidados aos pais.', null),
-- Fase 5
('p_ativacao', 'pediatrico', 'Ativação e programação', 'Ativação', 5, 1,
 'Ativação dos processadores', 'Ligar os processadores',
 'Audiologia pediátrica', '3 a 4 semanas após a cirurgia', 35,
 'Primeiro mapa com medidas objetivas (telemetria, reflexo estapédico). Registo dos processadores. Início da contagem da idade auditiva.', null),
('p_maps', 'pediatrico', 'Ativação e programação', 'Ativação', 5, 2,
 'Programações frequentes', 'Afinar o som',
 'Audiologia pediátrica', 'mensal no 1.º ano, depois trimestral', 400,
 'Audiometria condicionada por reforço visual ou lúdica, conforme a idade.', null),
-- Fase 6
('p_tav', 'pediatrico', 'Reabilitação, creche e escola', 'Escola', 6, 1,
 'Terapia auditivo-verbal', 'Terapia com a família na sala',
 'Terapia da fala', 'semanal', 400,
 'Quem treina a criança todos os dias são os pais.', null),
('p_escola', 'pediatrico', 'Reabilitação, creche e escola', 'Escola', 6, 2,
 'Articulação com creche e escola', 'Preparar a creche e a escola',
 'Gestor de caso + EMAEI', 'cada ano letivo', null,
 'Microfone remoto (FM), acústica e lugar na sala, medidas de suporte à aprendizagem. TEACH no início do ano letivo. Registo do tipo de escolaridade.',
 'A escolaridade é o maior benefício social do implante pediátrico; nos Países Baixos, só 35% das crianças implantadas frequentam o ensino regular no básico e 46% no secundário (Neve et al., 2021). Sem registo, este resultado não se mede.'),
('p_lgp', 'pediatrico', 'Reabilitação, creche e escola', 'Escola', 6, 3,
 'Acesso a LGP e a pares', 'Língua gestual e outras crianças surdas',
 'Equipa + associações', 'contínuo', null,
 'Direito da criança surda ao contacto com a comunidade surda, ouça ou não com o implante.', null),
-- Fase 7
('p_resultados', 'pediatrico', 'Resultados e transição', 'Transição', 7, 1,
 'Avaliação de resultados e da linguagem', 'Medir o que mudou',
 'Audiologia + terapia da fala', '3, 6, 12 meses e depois anual', 400,
 'Perceção da fala adequada à idade, marcos de linguagem por idade auditiva, questionários da faixa etária.', null),
('p_longo', 'pediatrico', 'Resultados e transição', 'Transição', 7, 2,
 'Seguimento anual', 'Consulta anual',
 'Equipa do CREIC', 'anual', null,
 'Moldes, acessórios, reavaliação escolar; MuRQoL a partir dos 12 anos se a música for importante.', null),
('p_upgrade', 'pediatrico', 'Resultados e transição', 'Transição', 7, 3,
 'Reavaliação e atualização dos processadores', 'Processadores mais recentes',
 'Audiologia pediátrica', 'a cada 5 a 6 anos', null,
 'Testes adequados à idade e questionários antes e depois do período de experiência.', null),
('p_transicao', 'pediatrico', 'Resultados e transição', 'Transição', 7, 4,
 'Transição para a área de adulto', 'Passar a tratar de tudo sozinho(a)',
 'Equipa do CREIC', 'entre os 16 e os 18 anos', null,
 'Questionário de preparação para a transição aos 16 e 17 anos; CIQOL-10 e SSQ12 começam antes, para a série não quebrar. Aos 18 anos o profissional passa o doente para o grupo adulto.',
 'Na revisão de 357 estudos sobre modelos de cuidados em implante coclear, nenhum avaliou intervenções de transição entre serviços (Ebrahimi-Madiseh et al., 2023). É uma lacuna, não uma prática estabelecida.')
on conflict (id) do update set
  grupo = excluded.grupo, fase = excluded.fase, fase_curta = excluded.fase_curta,
  fase_ordem = excluded.fase_ordem, ordem = excluded.ordem, titulo = excluded.titulo,
  titulo_simples = excluded.titulo_simples, quem = excluded.quem, prazo_texto = excluded.prazo_texto,
  prazo_dias = excluded.prazo_dias, nota = excluded.nota, evidencia = excluded.evidencia;


-- ============================================================================
-- 3. QUESTIONÁRIOS
-- ============================================================================
insert into questionarios
  (id, sigla, nome, tipo, grupo, idade_min, idade_max, respondente, nucleo, itens_n, minutos,
   momentos, dominios_icf, licenca, versao_pt, mcid, normas, definicao, notas)
values

-- ---------------------------------------------------------------- ADULTO: núcleo
('ciqol10', 'CIQOL-10 Global', 'Cochlear Implant Quality of Life — 10 Global', 'prom', 'adulto', 18, null, 'proprio', true, 10, 3,
 '{basal,3m,6m,12m,anual}', '{funcoes_corpo,atividades_participacao,fatores_ambientais}',
 'Gratuito para uso clínico e investigação (MUSC)', 'Sem versão portuguesa validada conhecida: tradução e adaptação necessárias', null, null,
 '{"demonstracao": true, "metodo": "media_0_100",
   "escala": {"min": 1, "max": 5, "rotulos": ["Nunca", "Raramente", "Às vezes", "Muitas vezes", "Sempre"]},
   "itens": [
     {"id": "g1", "texto": "Consigo conversar com uma pessoa num lugar sossegado sem ler os lábios."},
     {"id": "g2", "texto": "Consigo participar numa conversa de grupo à mesa."},
     {"id": "g3", "texto": "Consigo falar ao telefone com alguém conhecido."},
     {"id": "g4", "texto": "Sinto-me confiante nas situações em que tenho de ouvir."},
     {"id": "g5", "texto": "Consigo acompanhar um programa de televisão sem legendas."},
     {"id": "g6", "texto": "Consigo perceber de onde vem um som."},
     {"id": "g7", "texto": "Consigo ouvir durante muito tempo sem ficar exausto(a)."},
     {"id": "g8", "texto": "Participo em atividades sociais sem evitar situações por causa da audição."},
     {"id": "g9", "texto": "Consigo perceber o que me dizem num restaurante."},
     {"id": "g10", "texto": "Sinto-me incluído(a) nas conversas com família e amigos."}]}',
 'Instrumento global, desenhado com utilizadores de implante e metodologia PROMIS. Incluído na bateria mínima de testes atualizada (Kartal Ozcan et al., 2026).'),

('ssq12', 'SSQ12', 'Speech, Spatial and Qualities of Hearing Scale — versão curta', 'prom', 'adulto', 14, null, 'proprio', true, 12, 6,
 '{basal,3m,6m,12m,anual}', '{funcoes_corpo,atividades_participacao}',
 'Uso livre com citação', 'Versão portuguesa em uso (confirmar a versão adotada)', null, null,
 '{"demonstracao": true, "metodo": "media",
   "escala": {"min": 0, "max": 10, "rotulos": ["Nada", "Perfeitamente"], "extremos": true},
   "rotulos_subescalas": {"fala": "Audição da fala", "espacial": "Audição espacial", "qualidades": "Qualidades da audição"},
   "itens": [
     {"id": "s1", "subescala": "fala", "texto": "Numa conversa a dois, numa sala sossegada, consegue acompanhar?"},
     {"id": "s2", "subescala": "fala", "texto": "Num grupo, num lugar com ruído, consegue seguir a conversa?"},
     {"id": "s3", "subescala": "fala", "texto": "Com a televisão ligada, consegue acompanhar quem fala consigo?"},
     {"id": "s4", "subescala": "fala", "texto": "Quando a conversa passa de uma pessoa para outra, consegue acompanhar?"},
     {"id": "s5", "subescala": "fala", "texto": "Ao telefone com alguém conhecido, consegue perceber?"},
     {"id": "s6", "subescala": "espacial", "texto": "Consegue perceber de que lado vem um som?"},
     {"id": "s7", "subescala": "espacial", "texto": "Consegue perceber se um som se está a aproximar ou a afastar?"},
     {"id": "s8", "subescala": "espacial", "texto": "Consegue perceber a que distância está quem fala consigo?"},
     {"id": "s9", "subescala": "qualidades", "texto": "Consegue distinguir as vozes de pessoas conhecidas?"},
     {"id": "s10", "subescala": "qualidades", "texto": "Os sons do dia a dia parecem-lhe naturais?"},
     {"id": "s11", "subescala": "qualidades", "texto": "Consegue perceber a fala sem ter de se concentrar muito?"},
     {"id": "s12", "subescala": "qualidades", "texto": "Consegue ignorar um som de fundo e ouvir o que quer?"}]}',
 'A linguagem comum dos centros de implante: permite comparar com a literatura. Começa aos 14 anos na pediatria para atravessar a transição sem quebrar a série.'),

('hui3', 'HUI-3', 'Health Utilities Index Mark 3', 'prom', 'adulto', 18, null, 'proprio', true, 15, 5,
 '{basal,12m,anual}', '{funcoes_corpo}',
 'Licença paga (Health Utilities Inc.)', 'Confirmar versão portuguesa e licença', null, null, null,
 'Medida de utilidade para QALY. Ao contrário do SF-36 e do EQ-5D, tem atributo de audição: deteta a mudança do implante (SMD 0,84; McRackan et al., 2018) e foi a base do ganho de qualidade de vida na análise custo-benefício neerlandesa (0,17 unilateral, 0,21 bilateral; Neve et al., 2021). Aplicação e pontuação pelo sistema licenciado; a pontuação regista-se na ficha.'),

('prem_creic', 'PREM', 'Experiência com o CREIC', 'prem', 'adulto', 16, null, 'proprio', true, 6, 2,
 '{apos_marco}', '{fatores_ambientais}',
 'Instrumento local', 'Original em português', null, null,
 '{"demonstracao": false, "metodo": "media_0_100",
   "escala": {"min": 1, "max": 5, "rotulos": ["Discordo totalmente", "Discordo", "Nem concordo nem discordo", "Concordo", "Concordo totalmente"]},
   "itens": [
     {"id": "p1", "texto": "Recebi informação clara sobre a etapa em que estou e o que vem a seguir."},
     {"id": "p2", "texto": "A equipa comunicou comigo da forma que eu prefiro."},
     {"id": "p3", "texto": "Quando precisei de intérprete ou de outro apoio na consulta, esse apoio existiu."},
     {"id": "p4", "texto": "As minhas mensagens foram respondidas no prazo prometido."},
     {"id": "p5", "texto": "Senti que a minha opinião contou nas decisões sobre o meu tratamento."},
     {"id": "p6", "texto": "Os tempos de espera entre etapas foram-me explicados."}]}',
 'A OCDE recomenda medir experiência (PREMs) a par dos resultados (PROMs); os estudos sobre modelos de cuidados em implante coclear raramente o fazem (Ebrahimi-Madiseh et al., 2023).'),

-- ---------------------------------------------------------------- ADULTO: candidatura e perfil detalhado
('ciqol_exp', 'CIQOL-Expectations', 'Cochlear Implant Quality of Life — Expectations', 'expectativas', 'adulto', 18, null, 'proprio', false, 35, 10,
 '{candidatura_antes_aconselhamento,candidatura_depois_aconselhamento}', '{funcoes_corpo,atividades_participacao,fatores_ambientais}',
 'Gratuito, com manual de pontuação (MUSC)', 'Sem versão portuguesa validada conhecida: tradução e adaptação necessárias', null, null,
 '{"demonstracao": true, "metodo": "media_0_100",
   "escala": {"min": 1, "max": 5, "rotulos": ["Nunca", "Raramente", "Às vezes", "Muitas vezes", "Sempre"]},
   "rotulos_subescalas": {"comunicacao": "Comunicação", "emocional": "Emocional", "entretenimento": "Entretenimento", "ambiente": "Ambiente", "esforco_auditivo": "Esforço auditivo", "social": "Social"},
   "introducao": "Pense em como espera estar depois de um ano a usar o implante.",
   "itens": [
     {"id": "c1", "subescala": "comunicacao", "texto": "Vou conseguir conversar com uma pessoa num lugar sossegado sem ler os lábios."},
     {"id": "c2", "subescala": "comunicacao", "texto": "Vou conseguir participar numa conversa de grupo à mesa."},
     {"id": "e1", "subescala": "emocional", "texto": "Vou sentir-me confiante nas situações em que tenho de ouvir."},
     {"id": "e2", "subescala": "emocional", "texto": "Vou sentir-me tranquilo(a) quando não percebo à primeira."},
     {"id": "t1", "subescala": "entretenimento", "texto": "Vou gostar de ouvir música."},
     {"id": "t2", "subescala": "entretenimento", "texto": "Vou conseguir acompanhar televisão sem legendas."},
     {"id": "a1", "subescala": "ambiente", "texto": "Vou conseguir perceber de onde vem um som."},
     {"id": "a2", "subescala": "ambiente", "texto": "Vou conseguir ouvir numa sala com eco ou barulho de fundo."},
     {"id": "f1", "subescala": "esforco_auditivo", "texto": "Vou conseguir ouvir durante muito tempo sem ficar exausto(a)."},
     {"id": "f2", "subescala": "esforco_auditivo", "texto": "Ouvir não me vai exigir muito esforço ao longo do dia."},
     {"id": "o1", "subescala": "social", "texto": "Vou participar em atividades sociais sem evitar situações."},
     {"id": "o2", "subescala": "social", "texto": "Vou sentir-me incluído(a) nas conversas com família e amigos."}]}',
 'Mede o que o candidato espera, nos mesmos domínios do CIQOL-35. A plataforma compara cada domínio com a média + 1 DP de 705 utilizadores experientes e avisa quando a expectativa está acima. Não validado em pediatria nem em surdez unilateral (McRackan et al., 2022).'),

('ciqol35', 'CIQOL-35 Profile', 'Cochlear Implant Quality of Life — 35 Profile', 'prom', 'adulto', 18, null, 'proprio', false, 35, 10,
 '{basal,12m}', '{funcoes_corpo,atividades_participacao,fatores_ambientais}',
 'Gratuito para uso clínico e investigação (MUSC)', 'Sem versão portuguesa validada conhecida: tradução e adaptação necessárias', null,
 '{"comunicacao": {"media": 51.4, "dp": 13.3},
   "emocional": {"media": 64.7, "dp": 15.9},
   "entretenimento": {"media": 55.8, "dp": 23.0},
   "ambiente": {"media": 61.0, "dp": 17.7},
   "esforco_auditivo": {"media": 41.5, "dp": 14.8},
   "social": {"media": 67.7, "dp": 19.1},
   "global": {"media": 52.6, "dp": 10.9},
   "fonte": "Utilizadores com mais de 12 meses de implante, n = 705 (McRackan et al., 2022, tabela 3)"}',
 '{"demonstracao": true, "metodo": "media_0_100",
   "escala": {"min": 1, "max": 5, "rotulos": ["Nunca", "Raramente", "Às vezes", "Muitas vezes", "Sempre"]},
   "rotulos_subescalas": {"comunicacao": "Comunicação", "emocional": "Emocional", "entretenimento": "Entretenimento", "ambiente": "Ambiente", "esforco_auditivo": "Esforço auditivo", "social": "Social"},
   "itens": [
     {"id": "c1", "subescala": "comunicacao", "texto": "Consigo conversar com uma pessoa num lugar sossegado sem ler os lábios."},
     {"id": "c2", "subescala": "comunicacao", "texto": "Consigo participar numa conversa de grupo à mesa."},
     {"id": "e1", "subescala": "emocional", "texto": "Sinto-me confiante nas situações em que tenho de ouvir."},
     {"id": "e2", "subescala": "emocional", "texto": "Sinto-me tranquilo(a) quando não percebo à primeira."},
     {"id": "t1", "subescala": "entretenimento", "texto": "Gosto de ouvir música."},
     {"id": "t2", "subescala": "entretenimento", "texto": "Consigo acompanhar televisão sem legendas."},
     {"id": "a1", "subescala": "ambiente", "texto": "Consigo perceber de onde vem um som."},
     {"id": "a2", "subescala": "ambiente", "texto": "Consigo ouvir numa sala com eco ou barulho de fundo."},
     {"id": "f1", "subescala": "esforco_auditivo", "texto": "Consigo ouvir durante muito tempo sem ficar exausto(a)."},
     {"id": "f2", "subescala": "esforco_auditivo", "texto": "Ouvir não me exige muito esforço ao longo do dia."},
     {"id": "o1", "subescala": "social", "texto": "Participo em atividades sociais sem evitar situações."},
     {"id": "o2", "subescala": "social", "texto": "Sinto-me incluído(a) nas conversas com família e amigos."}]}',
 'Substitui o NCIQ como perfil detalhado: 35 itens, seis domínios e cobertura das três componentes da CIF, com melhores propriedades psicométricas (Kartal Ozcan et al., 2026). Pontuação oficial por tabelas do manual; a transformação 0–100 aqui usada é provisória.'),

-- ---------------------------------------------------------------- ADULTO: módulos
('eq5d5l', 'EQ-5D-5L', 'EuroQol 5 dimensões, 5 níveis', 'prom', 'ambos', 16, null, 'proprio', false, 6, 2,
 '{basal,12m}', '{funcoes_corpo,atividades_participacao}',
 'Registo na EuroQol', 'Versão portuguesa validada', null, null, null,
 'Opcional, para comparação com outras patologias e com dados nacionais. Não tem dimensão de audição nem itens de fatores ambientais (Kartal Ozcan et al., 2026): subestima o benefício do implante. A utilidade para QALY usa o HUI-3.'),

('nciq', 'NCIQ', 'Nijmegen Cochlear Implant Questionnaire', 'prom', 'ambos', 12, null, 'proprio', false, 60, 15,
 '{basal,12m}', '{funcoes_corpo,atividades_participacao,fatores_ambientais}',
 'Uso livre com citação', 'Versão portuguesa disponível (confirmar)', null, null, null,
 'O mais usado na literatura (58% dos estudos) e o que cobre mais subdomínios da CIF (14 de 22), mas 60 itens causam fadiga de resposta e há dúvidas sobre a precisão de medida (Kartal Ozcan et al., 2026). Manter só se for preciso comparar com séries antigas.'),

('aphab', 'APHAB', 'Abbreviated Profile of Hearing Aid Benefit', 'prom', 'adulto', 18, null, 'proprio', false, 24, 8,
 '{prova_protese_inicio,prova_protese_fim,upgrade_antes,upgrade_depois}', '{funcoes_corpo,atividades_participacao,fatores_ambientais}',
 'Uso livre com citação', 'Confirmar versão portuguesa', 3.8, null,
 '{"demonstracao": true, "metodo": "aphab",
   "escala": {"min": 1, "max": 7, "rotulos": ["Sempre (99%)", "Quase sempre (87%)", "Geralmente (75%)", "Metade das vezes (50%)", "Ocasionalmente (25%)", "Raramente (12%)", "Nunca (1%)"]},
   "rotulos_subescalas": {"EC": "Facilidade de comunicação", "BN": "Ruído de fundo", "RV": "Reverberação", "AV": "Aversão a sons"},
   "itens": [
     {"id": "ec1", "subescala": "EC", "invertido": true, "texto": "Percebo o que me dizem numa conversa calma em casa."},
     {"id": "ec2", "subescala": "EC", "invertido": false, "texto": "Tenho de pedir às pessoas que repitam, mesmo a sós com elas."},
     {"id": "bn1", "subescala": "BN", "invertido": false, "texto": "Tenho dificuldade em perceber num café movimentado."},
     {"id": "bn2", "subescala": "BN", "invertido": true, "texto": "Percebo quem fala comigo mesmo com outras conversas à volta."},
     {"id": "rv1", "subescala": "RV", "invertido": true, "texto": "Numa sala grande com eco, percebo bem quem fala."},
     {"id": "rv2", "subescala": "RV", "invertido": false, "texto": "Numa igreja ou auditório, perco partes do que é dito."},
     {"id": "av1", "subescala": "AV", "invertido": false, "texto": "Os sons altos inesperados incomodam-me."},
     {"id": "av2", "subescala": "AV", "invertido": false, "texto": "O barulho do trânsito é desagradável para mim."}]}',
 'Na prova de próteses documenta o benefício insuficiente. Na atualização do processador, diferença mínima relevante de 3,8 pontos percentuais na pontuação global (Lailach et al., 2023). Global = média de EC, BN e RV.'),

('apsq', 'APSQ', 'Audio Processor Satisfaction Questionnaire', 'prom', 'ambos', 12, null, 'proprio', false, 15, 5,
 '{upgrade_antes,upgrade_depois}', '{atividades_participacao,fatores_ambientais}',
 'Contactar autores', 'Validado em alemão; versão portuguesa por fazer', 0.74, null,
 '{"demonstracao": true, "metodo": "media",
   "escala": {"min": 0, "max": 10, "rotulos": ["Discordo totalmente", "Concordo totalmente"], "extremos": true},
   "rotulos_subescalas": {"conforto": "Conforto", "vida_social": "Vida social", "usabilidade": "Usabilidade"},
   "itens": [
     {"id": "k1", "subescala": "conforto", "texto": "O processador é confortável durante todo o dia."},
     {"id": "k2", "subescala": "conforto", "texto": "Esqueço-me de que tenho o processador posto."},
     {"id": "k3", "subescala": "vida_social", "texto": "Com o processador, participo com facilidade em conversas sociais."},
     {"id": "k4", "subescala": "vida_social", "texto": "O processador ajuda-me em restaurantes e reuniões."},
     {"id": "k5", "subescala": "usabilidade", "texto": "É fácil mudar os programas e o volume."},
     {"id": "k6", "subescala": "usabilidade", "texto": "É fácil ligar o processador ao telemóvel ou a outros aparelhos."}]}',
 'Satisfação com o processador em três subescalas de 5 itens (0–10). Diferença mínima relevante de 0,74 pontos na pontuação global (Lailach et al., 2023).'),

('murqol', 'MuRQoL', 'Music-Related Quality of Life', 'prom', 'ambos', 12, null, 'proprio', false, 36, 10,
 '{12m,anual}', '{atividades_participacao,fatores_ambientais}',
 'Contactar autores', 'Versão italiana validada; versão portuguesa por fazer', null, null,
 '{"demonstracao": true, "metodo": "murqol",
   "escalas": {
     "frequencia": {"min": 1, "max": 5, "rotulos": ["Nunca", "Raramente", "Às vezes", "Muitas vezes", "Sempre"]},
     "importancia": {"min": 1, "max": 5, "rotulos": ["Nada importante", "Pouco importante", "Moderadamente", "Muito importante", "Extremamente importante"]}},
   "rotulos_seccoes": {"frequencia": "Com que frequência consegue…", "importancia": "Quão importante é para si…"},
   "itens": [
     {"id": "f1", "seccao": "frequencia", "subescala": "percecao", "texto": "Reconhecer melodias que conhece."},
     {"id": "f2", "seccao": "frequencia", "subescala": "percecao", "texto": "Distinguir instrumentos numa música."},
     {"id": "f3", "seccao": "frequencia", "subescala": "envolvimento", "texto": "Ouvir música por iniciativa própria."},
     {"id": "f4", "seccao": "frequencia", "subescala": "envolvimento", "texto": "Ir a concertos ou a eventos com música."},
     {"id": "i1", "seccao": "importancia", "subescala": "percecao", "texto": "Reconhecer melodias que conhece."},
     {"id": "i2", "seccao": "importancia", "subescala": "percecao", "texto": "Distinguir instrumentos numa música."},
     {"id": "i3", "seccao": "importancia", "subescala": "envolvimento", "texto": "Ouvir música por iniciativa própria."},
     {"id": "i4", "seccao": "importancia", "subescala": "envolvimento", "texto": "Ir a concertos ou a eventos com música."}]}',
 'Duas secções espelho (frequência e importância). Fator de reabilitação = importância − frequência, quando a importância é ≥ 2: indicou vontade de reabilitação musical em 63% de 73 doentes, e aplicou-se a partir dos 12 anos (Frosolini et al., 2022).'),

('thi', 'THI', 'Tinnitus Handicap Inventory', 'prom', 'adulto', 18, null, 'proprio', false, 25, 7,
 '{basal,6m,12m}', '{funcoes_corpo,atividades_participacao}',
 'Uso livre com citação', 'Versão portuguesa validada', null, null, null,
 'Só com queixa de acufeno. O acufeno costuma melhorar com o implante — se não for medido, a melhoria não fica registada.'),

('dhi', 'DHI', 'Dizziness Handicap Inventory', 'prom', 'adulto', 18, null, 'proprio', false, 25, 7,
 '{pre_cirurgia,3m}', '{funcoes_corpo,atividades_participacao}',
 'Uso livre com citação', 'Versão portuguesa validada', null, null, null,
 'Só com queixa ou risco vestibular. A cirurgia pode afetar a função vestibular: medir antes protege o doente e o centro.'),

('hads', 'HADS', 'Hospital Anxiety and Depression Scale', 'prom', 'adulto', 18, null, 'proprio', false, 14, 5,
 '{basal,12m}', '{funcoes_corpo}',
 'Licença (GL Assessment)', 'Versão portuguesa validada', null, null, null,
 'Com a psicologia. A surdez adquirida isola; identifica quem precisa de acompanhamento antes da cirurgia.'),

('esforco', 'Esforço auditivo', 'Escala de esforço e fadiga auditiva', 'prom', 'ambos', 12, null, 'proprio', false, 4, 2,
 '{basal,6m,12m}', '{funcoes_corpo,atividades_participacao}',
 'Instrumento local', 'Original em português', null, null,
 '{"demonstracao": false, "metodo": "media",
   "escala": {"min": 0, "max": 10, "rotulos": ["Nenhum", "Extremo"], "extremos": true},
   "introducao": "Pense na última semana. 0 é nenhum, 10 é o máximo que consegue imaginar.",
   "itens": [
     {"id": "e1", "texto": "Quanto esforço fez para ouvir, num dia típico?"},
     {"id": "e2", "texto": "Quão cansado(a) ficou ao fim do dia por causa do esforço para ouvir?"},
     {"id": "e3", "texto": "Quanto evitou situações por antecipar o esforço de ouvir?"},
     {"id": "e4", "texto": "Quanto esse cansaço afetou o trabalho, os estudos ou as tarefas de casa?"}]}',
 'Pontuação mais alta = mais esforço. O esforço auditivo é o domínio em que as expectativas mais se afastam do resultado típico (McRackan et al., 2022), e os testes de cabine não o captam.'),

-- ---------------------------------------------------------------- PEDIATRIA
('littlears', 'LittlEARS', 'LittlEARS Auditory Questionnaire', 'prom', 'pediatrico', 0, 2, 'cuidador', true, 35, 8,
 '{basal,ativacao,1m,3m,6m,9m,12m}', '{funcoes_corpo,atividades_participacao}',
 'Registo junto do editor', 'Versão portuguesa disponível (confirmar edição)', null, null,
 '{"demonstracao": true, "metodo": "soma",
   "escala": {"min": 0, "max": 1, "rotulos": ["Não", "Sim"]},
   "introducao": "Responda sobre o que viu a criança fazer, sem contar com ela ver quem fala.",
   "itens": [
     {"id": "l1", "texto": "Reage quando alguém a chama pelo nome."},
     {"id": "l2", "texto": "Vira-se para procurar um som que não vê."},
     {"id": "l3", "texto": "Acalma-se ou sorri ao ouvir uma voz conhecida."},
     {"id": "l4", "texto": "Imita sons ou entoações que ouve."},
     {"id": "l5", "texto": "Reage a sons do dia a dia (campainha, cão, aspirador)."},
     {"id": "l6", "texto": "Faz um gesto ou um som quando ouve uma música de que gosta."}]}',
 'Idades em anos de IDADE AUDITIVA (0–24 meses desde a ativação). Tem curva normativa: mostra se a criança progride ao ritmo esperado.'),

('itmais', 'IT-MAIS', 'Infant-Toddler Meaningful Auditory Integration Scale', 'prom', 'pediatrico', 0, 3, 'cuidador', false, 10, 10,
 '{basal,3m,6m,12m}', '{funcoes_corpo,atividades_participacao}',
 'Uso livre com citação', 'Versão portuguesa em uso (confirmar)', null, null, null,
 'Entrevista estruturada aos pais: funciona com baixa literacia. Pontuação regista-se na ficha.'),

('peach', 'PEACH', 'Parents Evaluation of Aural/Oral Performance of Children', 'prom', 'pediatrico', 0, 12, 'cuidador', true, 13, 10,
 '{3m,6m,12m,anual}', '{atividades_participacao,fatores_ambientais}',
 'Uso livre com citação', 'Confirmar versão portuguesa', null, null,
 '{"demonstracao": true, "metodo": "media_0_100",
   "escala": {"min": 0, "max": 4, "rotulos": ["Nunca", "Raramente (até 25%)", "Às vezes (até 50%)", "Muitas vezes (até 75%)", "Quase sempre (mais de 75%)"]},
   "rotulos_subescalas": {"silencio": "Em silêncio", "ruido": "No ruído"},
   "introducao": "Pense na última semana e em situações concretas.",
   "itens": [
     {"id": "q1", "subescala": "silencio", "texto": "Em casa, sem barulho, responde quando a chamam pelo nome?"},
     {"id": "q2", "subescala": "silencio", "texto": "Numa conversa calma, percebe o que lhe dizem sem ver a boca?"},
     {"id": "q3", "subescala": "ruido", "texto": "Com a televisão ligada, responde quando a chamam?"},
     {"id": "q4", "subescala": "ruido", "texto": "Na rua ou no parque, percebe o que lhe dizem?"}]}',
 'Pede exemplos concretos da última semana, o que reduz a resposta por impressão geral.'),

('mais_muss', 'MAIS / MUSS', 'Meaningful Auditory Integration Scale / Meaningful Use of Speech Scale', 'prom', 'pediatrico', 3, 5, 'cuidador', false, 20, 15,
 '{6m,12m,anual}', '{funcoes_corpo,atividades_participacao}',
 'Uso livre com citação', 'Versão portuguesa em uso (confirmar)', null, null, null,
 'Continuação do IT-MAIS quando a criança cresce. Pontuação regista-se na ficha.'),

('teach', 'TEACH', 'Teachers Evaluation of Aural Performance of Children', 'prom', 'pediatrico', 3, 12, 'professor', false, 11, 10,
 '{inicio_ano_letivo,fim_ano_letivo}', '{atividades_participacao,fatores_ambientais}',
 'Uso livre com citação', 'Confirmar versão portuguesa', null, null, null,
 'A sala de aula é o pior ambiente acústico da vida da criança. Preenchido pela educadora ou professor; registado na ficha.'),

('ccipp', 'CCIPP', 'Children with Cochlear Implants: Parental Perspectives', 'prom', 'pediatrico', 3, 12, 'cuidador', false, 74, 20,
 '{12m,bienal}', '{atividades_participacao,fatores_ambientais}',
 'Contactar autores', 'Confirmar versão portuguesa', null, null, null,
 'Oito domínios da perspetiva dos pais, incluindo o processo de decisão e o apoio recebido.'),

('pedsql', 'PedsQL 4.0', 'Pediatric Quality of Life Inventory — Generic Core', 'prom', 'pediatrico', 2, 18, 'cuidador', false, 23, 5,
 '{basal,anual}', '{funcoes_corpo,atividades_participacao}',
 'Licença (Mapi Research Trust)', 'Versão portuguesa validada', null, null, null,
 'Qualidade de vida genérica por faixas (2–4, 5–7, 8–12, 13–18). A partir dos 8 anos responder também a versão da criança.'),

('hearql', 'HEAR-QL', 'Hearing Environments and Reflection on Quality of Life (26 e 28)', 'prom', 'pediatrico', 7, 18, 'crianca_apoio', false, 26, 10,
 '{basal,6m,12m,anual}', '{atividades_participacao,fatores_ambientais}',
 'Contactar autores', 'Confirmar versão portuguesa', null, null, null,
 'Versão 26 itens (7–12 anos) e 28 itens (13–18). A criança passa a ser a melhor fonte sobre a sua própria vida.'),

('vfs_peds', 'VFS-Peds', 'Vanderbilt Fatigue Scale — pediátrica', 'prom', 'pediatrico', 6, 17, 'crianca_apoio', false, 10, 5,
 '{anual}', '{funcoes_corpo,atividades_participacao}',
 'Contactar autores', 'Confirmar versão portuguesa', null, null, null,
 'Fadiga relacionada com a audição, em versões da criança, dos pais e do professor. Sem medir, confunde-se fadiga com desinteresse.'),

('transicao', 'Transição', 'Preparação para a transição para a área de adulto', 'prom', 'pediatrico', 16, 18, 'proprio', false, 6, 3,
 '{16a,17a}', '{atividades_participacao,fatores_ambientais}',
 'Instrumento local', 'Original em português', null, null,
 '{"demonstracao": false, "metodo": "media_0_100",
   "escala": {"min": 1, "max": 5, "rotulos": ["Ainda não sei", "Sei com muita ajuda", "Sei com alguma ajuda", "Sei quase sozinho(a)", "Sei sozinho(a)"]},
   "itens": [
     {"id": "t1", "texto": "Explicar a minha surdez e o implante a alguém que não conheço."},
     {"id": "t2", "texto": "Marcar ou remarcar uma consulta."},
     {"id": "t3", "texto": "Resolver uma avaria do processador."},
     {"id": "t4", "texto": "Pedir intérprete ou outros apoios na escola, na faculdade ou no trabalho."},
     {"id": "t5", "texto": "Falar com a equipa na consulta sem os meus pais responderem por mim."},
     {"id": "t6", "texto": "Saber o que os meus pais podem ver do meu processo e como isso muda aos 18 anos."}]}',
 'A transição falha quando o jovem chega à área de adulto sem nunca ter falado por si.'),

('prem_creic_ped', 'PREM (família)', 'Experiência da família com o CREIC', 'prem', 'pediatrico', 0, 18, 'cuidador', true, 6, 2,
 '{apos_marco}', '{fatores_ambientais}',
 'Instrumento local', 'Original em português', null, null,
 '{"demonstracao": false, "metodo": "media_0_100",
   "escala": {"min": 1, "max": 5, "rotulos": ["Discordo totalmente", "Discordo", "Nem concordo nem discordo", "Concordo", "Concordo totalmente"]},
   "itens": [
     {"id": "p1", "texto": "Recebemos informação clara sobre a etapa em que a criança está e o que vem a seguir."},
     {"id": "p2", "texto": "A equipa comunicou connosco da forma que preferimos."},
     {"id": "p3", "texto": "Quando precisámos de intérprete ou de outro apoio, esse apoio existiu."},
     {"id": "p4", "texto": "As nossas mensagens foram respondidas no prazo prometido."},
     {"id": "p5", "texto": "Sentimos que a nossa opinião contou nas decisões."},
     {"id": "p6", "texto": "A equipa ajudou-nos na articulação com a creche ou a escola."}]}',
 'Versão da família do PREM do centro.')

on conflict (id) do update set
  sigla = excluded.sigla, nome = excluded.nome, tipo = excluded.tipo, grupo = excluded.grupo,
  idade_min = excluded.idade_min, idade_max = excluded.idade_max, respondente = excluded.respondente,
  nucleo = excluded.nucleo, itens_n = excluded.itens_n, minutos = excluded.minutos,
  momentos = excluded.momentos, dominios_icf = excluded.dominios_icf, licenca = excluded.licenca,
  versao_pt = excluded.versao_pt, mcid = excluded.mcid, normas = excluded.normas,
  definicao = excluded.definicao, notas = excluded.notas;
